### ISSUE TITLE
[Bug]: Titles are not being reinserted properly

### ISSUE THREAD

**Issue by fortiersteven** [lifebottle/PythonLib#103]
### Is it related to a specific Tales of game?

Tales of Rebirth (PS2)

### Contact Details

Stewie

### What happened?

Issues with Title displaying in the Menu:
![image](https://user-images.githubusercontent.com/74146408/222968516-695c3411-9a9e-49a3-8985-47afec35acea.png)
![image](https://user-images.githubusercontent.com/74146408/222968530-9ed488d8-1903-400b-ae44-d4d8b76e7554.png)

Title displaying in the Story
![image](https://user-images.githubusercontent.com/74146408/222968547-872650ad-7d21-4a70-b700-6c3c5e0ef773.png)
![image](https://user-images.githubusercontent.com/74146408/222968554-86136b6c-e0f7-42fe-b387-32e384188655.png)

**Comment by fortiersteven** [comment]
Need to check if its still relevant with the session we had yesterday

**Comment by Fis-Ura** [comment]
@fortiersteven This is solved with current build 2023_05_15 but the strategy menu is still broken
![image](https://github.com/lifebottle/PythonLib/assets/77898683/1d5ae43c-cd37-4dff-9c86-669114352dff)
