### ISSUE TITLE
[Bug]: Skit 14781 has an issue with the title

### ISSUE THREAD

**Issue by fortiersteven** [lifebottle/PythonLib#104]
### Is it related to a specific Tales of game?

Tales of Rebirth (PS2)

### Contact Details

Lauren

### What happened?

**What happened**

When we load the skit14781, the skit is not showing the right name
![image](https://github.com/lifebottle/PythonLib/assets/74146408/7e1b6196-c5ca-47ca-a091-4caa747000fb)
![image](https://github.com/lifebottle/PythonLib/assets/74146408/5f99adc3-e96d-42da-9a5a-50ef85905ed6)

**Detail**
- 14781.xml
- Skit title is stored inside the xml (not in SLPS)

**Comment by fortiersteven** [comment]
@SymphoniaLauren 
When you have some time,
can you tell us where the skit is in the Rabbits village?
Thx

**Comment by Fis-Ura** [comment]
@fortiersteven this seems fixed 
![image](https://github.com/lifebottle/PythonLib/assets/77898683/4085ca7b-8762-487d-a14e-16b31f53a228)

**Comment by Mc-muffin** [comment]
Seems it was fixed las time, so this is closed unless it pops up again (in which case, just reopen this issue)
