### ISSUE TITLE
[Bug]: Directions Board are not working as expected

### ISSUE THREAD

**Issue by fortiersteven** [lifebottle/PythonLib#106]
### Is it related to a specific Tales of game?

Tales of Rebirth (PS2)

### Contact Details

Pegi

### What happened?

**What happened**

**Details**
- Text is stored in 10232 and 10233

**Comment by fortiersteven** [comment]
@Fis-Ura Peux-tu aller mettre une image pour le what happened?
Thx

**Comment by Fis-Ura** [comment]
The notice inside of the Iron Factory are broken see bellow also Lauren said that (But if you go in the factory and look at stuff the unk tags that get the characters names are borked and crash everything) 
There's a memory card attached with the first save near the location.
[_RebirthBrokenSelectNotice.zip](https://github.com/lifebottle/PythonLib/files/11482746/_RebirthBrokenSelectNotice.zip)
![image](https://github.com/lifebottle/PythonLib/assets/77898683/654445a7-2e0f-4a64-9386-b174ec549c5f)
![image](https://github.com/lifebottle/PythonLib/assets/77898683/91d89b78-72c3-49d2-a1ba-d712dd285617)
![image](https://github.com/lifebottle/PythonLib/assets/77898683/13759200-d6b9-4a03-bbd0-942b6ca92ae4)

**Comment by Fis-Ura** [comment]
still broken also when interacting with some door it also crashes the game Lauren suspect the unk for the door and the linebreak for the notice

**Comment by Mc-muffin** [comment]
fixed as of SymphoniaLauren/Tales-of-Rebirth@a409aab and the last PR #108 (around 73f4f8d, probably)
