### ISSUE TITLE
[Bug]: Vertex Explosion for hilda on the world map

### ISSUE THREAD

**Issue by Fis-Ura** [lifebottle/PythonLib#107]
### Is it related to a specific Tales of game?

All games

### Contact Details

Pegi

### What happened?

When switching to hilda on the world map she goes into vertex explosion mode, this is not the case for the base game. you can use the save at 56:10 to see the behavior
[_RebirthHildaVertex.zip](https://github.com/lifebottle/PythonLib/files/11482839/_RebirthHildaVertex.zip)

![image](https://github.com/lifebottle/PythonLib/assets/77898683/c03c82e8-4b54-479d-90f3-27f80d98b97b)

**Comment by Mc-muffin** [comment]
Now this isn't technically Pythonlib's fault, and the issue has a known fix, but there's a balancing act of patch size and this fix, so for now this one remains open even if the current patch can side-step this specific issue.
![Tales of Rebirth_SLPS-25450_20230809215247](https://github.com/lifebottle/PythonLib/assets/8714476/63a0d07b-fd08-4ce3-846e-cd8bcdb382b0)

**Comment by Mc-muffin** [comment]
As of bf0ae1e this is no longer an issue as the files can't overlap each other, plus the patch size didn't explode, so closing this.
