### ISSUE TITLE
Investigate the way Rebirth finds the name for the text box

### ISSUE THREAD

**Issue by Fis-Ura** [lifebottle/PythonLib#70]
We need to find the way the game match the name with the textbox for future implementation.

**Comment by Mc-muffin** [comment]
Okay, small write-up on how does this work and why this needed investigation:

### Current Status:
Our current dumps just linearly search for text offsets inside the code section of the THEIRSCE files, which results in false occasional positives and in deattached name-text pairs, like so:

```
<Tytree>
Man, I can't handle
spicy food...
```

**Comment by Mc-muffin** [comment]
Okay, small write-up on how does this work and why this needed investigation:

## Current Status:
Our current dumps just linearly search for text offsets inside the code section of the THEIRSCE files, which results in occasional false positives and in deattached name-text pairs, like so:

| Text                                 |
|----------------------------|
| \<Annie\>  |
| What a peculiar flavor...  | 
| \<Tytree\> |
| Man, I can't handle<br>spicy food..|

This is fine for detection (one can just lump pairs together) but breaks once NPC's are involved, NPC's only register their name once, so we end up with lines like this:
| Text                                 |
|----------------------------|
| Woman  |
| Claire was walking back<br>to her house just now.  | 
| I squealed when I saw her...<br>Is she... back to normal? |
| Oh, are you a friend of<br>\<Veigue\>? Nice to meet you. |

And the context is now lost, adding heuristics while possible might be troublesome, so we better just find out how the game does its magic.

## How the game does it
If we check out a THEIRSCE file we can identify 4 major sections:
```
- Header
MAGIC -> `THEIRSCE` (always)
uint  -> offset to start of Code section
uint  -> offset to start of Text section

- Offsets 
short[] -> offsets inside bytecode section

- Code
code

- Text
list of null terminated strings
```

Much like DC here we also have some custom bytecode inside the THEIRSCE file, via reverse engineering we can know the command's width and have some understanding of their functionality, the part we are interested in is related to the textboxes, so here's the relevant info:

### Dialog calls
A regular story dialog call (from 10247.theirsce) looks like this:
```
0x900: C0       - PUSH   0
0x901: CA 00    - PUSH   0x200
0x903: C7       - PUSH   -1
0x904: C1       - PUSH   1
0x905: C0       - PUSH   0
0x906: C0       - PUSH   0
0x907: F8 1A 00 - PUSH.S "<Veigue>"
0x90A: F8 20 00 - PUSH.S "<voiceID:B000000>何者だ……なぜオレの\n名前を知っている……"
0x90D: E0 45    - CALL   0x45 (textbox_function)
```
There we can see that before the call to the textbox function both the text and the name is referenced using the `0xF8` opcode (plus 6 other parameters).
The NPC dialog calls look virtually the same, but they use a "reference" to the first name like:
```
// Start of NPC code, a "reference" to the name is set
0x53D: F7 00 00 - STACK_RESERVE 0
0x540: 48 20 04 - PTR_VAR 0x0420
0x543: F8 68 00 - PUSH.S "女の人"
0x546: 9B       - ASSIGN
[Flags checking code here]

// After checking flags, the code for the textbox is the same
// but the name uses the reference from before
0x576: C0       - PUSH   0
0x577: CA 00    - PUSH   0x0200
0x579: C7       - PUSH   -1
0x57A: C8 8A    - PUSH   0x8A
0x57C: C0       - PUSH   0
0x57D: C0       - PUSH   0
0x57E: 48 20 04 - PTR_VAQR   0x0420
0x581: F8 6F 00 - PUSH.S "さっき、クレアが家の方に\n歩いていったわよ。"
0x584: E0 45    - SYSCALL   0x45 (textbox_function)
```

With this info we can now identify what goes where:
- For regular textboxes we can just scan for calls to `0x45` and we'll know that the first string will always be the name and the second will always be the text
- For NPC textboxes we can store the current reference (by scanning for a `0x9B` preceded by `0xF8`) then if a `0x45` call has only 1 `0xF8` we'll use the reference as the name

**Comment by fortiersteven** [comment]
I'm good with this issue. 
Great work @Mc-muffin .
