### ISSUE TITLE
Investigate Menu files that we are missing

### ISSUE THREAD

**Issue by fortiersteven** [lifebottle/PythonLib#77]
### Is it related to a specific Tales of game?

Tales of Rebirth (PS2)

### Contact Details

Stewie

### What is your request?

**Problem**
We still don't have the menus files XMLs used for 
- Triangle Menu (buttons)
- Shop
- Artes
- Strategies
- Cooking
![image](https://user-images.githubusercontent.com/74146408/183252334-698bd092-8b31-402e-bae3-29a5b4350c85.png)

**What to do**
Those are probably MD1 files inside DAT.bin

Use these 3 buttons to find all the interesting MD1
- 決定
- あらすじブック
- 戻る

For each of the MD1 files, update one of the button with 
File_1, File_2, File_3

Make a new patch with those new MD1 and go in the different shop/menu to be able to map the 
MD1 to the menu

At the end, we should have an Excel file with 
MD1 file | Menu

**Comment by Fis-Ura** [comment]
@fortiersteven For the triangle menu it seems to be a problem where the tags are not the format we use, for both the japanese and the english

**Comment by Mc-muffin** [comment]
Updating this:
| Menu | File | Commit |
|--------|-----|----------|
| Triangle Menu | 11181.pak3 file 6 | SymphoniaLauren/Tales-of-Rebirth@7175dc85 |
| Shop | 11222.ovl & 11228.ovl | SymphoniaLauren/Tales-of-Rebirth@f227b057 |
| Monster Book | 1117.ovl | SymphoniaLauren/Tales-of-Rebirth@f227b057 |
| Synopsis | 11190.bin | SymphoniaLauren/Tales-of-Rebirth@f227b057 |
| Character Bios | 11191.bin | SymphoniaLauren/Tales-of-Rebirth@f227b057 |
| Sound Menu | 11225.ovl | SymphoniaLauren/Tales-of-Rebirth@f227b057 |
| Grade Menu | 11230.ovl | SymphoniaLauren/Tales-of-Rebirth@f227b057 |
| Title Screen | 00017.bin | SymphoniaLauren/Tales-of-Rebirth@8b6eb284 |
| Credits | 00020.bin | SymphoniaLauren/Tales-of-Rebirth@8b6eb284 |
| 3D Map | 00013.pak3 file 2 | SymphoniaLauren/Tales-of-Rebirth@52efdbf0 |

Artes, Strategy and Cooking seem to have been in SLPS before, with that said I'm closing this, if there's any other menu missing feel free to reopen.
