### ISSUE TITLE
[Feature]: Extract Shop menu to XML

### ISSUE THREAD

**Issue by fortiersteven** [lifebottle/PythonLib#78]
### Is it related to a specific Tales of game?

Tales of Rebirth (PS2)

### Contact Details

Stewie

### What is your request?

**Problem**
We would like to start working on translating the Shop menu but we don't have the XML yet.

**What to do**
Based on the previous story to investigate the menu file, use the MD1 found for shop menu and add a new file in the MenuFiles.json for Shop menu. Run the Python script to extract the XML and store it on the Repo

**Acceptance Criteria**
- New file is added in MenuFiles.json with content that make sense
- XML is added to Rebirth repo
- Python function extract_Menu_File is able to run without issue for the Shop MD1 file

**Comment by Mc-muffin** [comment]
Closing in favor of #77
