### ISSUE TITLE
[Bug]: Fix reinsertion of PAK3 file into DAT.bin

### ISSUE THREAD

**Issue by fortiersteven** [lifebottle/PythonLib#79]
### Is it related to a specific Tales of game?

Tales of Rebirth (PS2)

### Contact Details

Stewie

### What happened?

**Problem**
When I try to reinsert the PAK3 file 11181.pak3 based on our new translation. This introduced some weird graphic bugs in the Item Menus, Artes menu
![image](https://user-images.githubusercontent.com/74146408/183252709-e7482dff-c82c-4f83-aa96-f521c9d492b9.png)

FYI: Reinserting only SLPS with every sections translated doens't crite this weird glitch. That's why I'm pretty sure it is related to the PAK3 not being repacked properly.

**What to Do**
- Find the problem and document it
- Fix the issue in the pack_Menu_File function of PythonLib

**Comment by fortiersteven** [comment]
@Mc-muffin Is it something that we have encountered in DC?
Feels like Lauren talked about something like this ...

**Comment by Mc-muffin** [comment]
> @Mc-muffin Is it something that we have encountered in DC? Feels like Lauren talked about something like this ...

Yeah we had a (probably) similar issue on DC, it was related to images not being aligned inside the PAK file, the problem was fixed on furiousg4m3r/Tales-of-Destiny-DC#619, which added a pakcomposer flag to align certain files on insertion, before that there was fixer script on the repo.
We could add something similar here, assuming it's the same problem.

**Comment by fortiersteven** [comment]
Damn, both pak3 files repacked are so different. Lot of missing 0 in there plus additional infos in the header.

**Original**
![Image](https://user-images.githubusercontent.com/74146408/183527805-47560839-c619-4104-8af9-5d886f4467dc.png)

**Repacked**
![Image](https://user-images.githubusercontent.com/74146408/183527832-fdf59f1c-9125-4920-8498-fb7579edfc1b.png)




**Link to files**
[Files](https://drive.google.com/drive/folders/1whBxqdw4SeXu_Uea5rFhcsEmaTDHIoNk?usp=sharing)

**Used**
pakcomposer -d 11181.pak3 -3 -v -u -x
pakcomposer -c 11181 -3 -v -u -x

**Comment by Mc-muffin** [comment]
As of 96ef521 the whole menu insertion was remade, as a result we no longer make use of pakcomposer, instead relying on a python tool to manipulate PAK files.
Further, as of 9035c29 the PAK files get aligned on save if the original file was, the alignment is not to 0x100 mind you, but to 0x10, which is equivalent for our purpose.


![Tales of Rebirth_SLPS-25450_20230809214439](https://github.com/lifebottle/PythonLib/assets/8714476/f032344d-5045-4d15-8a7c-9369b890e3dd)
