### ISSUE TITLE
[Bug]: Missing Kanji at Extraction

### ISSUE THREAD

**Issue by Fis-Ura** [lifebottle/PythonLib#88]
See picture for list of files with missing Kanji

![Image](https://user-images.githubusercontent.com/77898683/184708345-7d3a2b62-c0ad-4bf5-9de9-8cccedab1368.png)
![Image](https://user-images.githubusercontent.com/77898683/184708440-307849a1-9612-402c-9867-0832fcfeb239.png)

**Comment by fortiersteven** [comment]
Related to PR https://github.com/SymphoniaLauren/Tales-of-Rebirth/pull/33
on Lauren's repo

**Comment by fortiersteven** [comment]
Code used [here](https://drive.google.com/file/d/1Bqlv0PwohPqPBJLbucfE2HMdDqhBxD4a/view?usp=sharing)
