### ISSUE TITLE
[Feature]: Update script to remove voiceId for NDX and Rebirth

### ISSUE THREAD

**Issue by fortiersteven** [lifebottle/PythonLib#96]
### Is it related to a specific Tales of game?

All games

### Contact Details

Stewie

### What is your request?

**Problem**
Translation app show the VoiceId when we translate and the problem is the text is not well aligned. It would be more in line with what we see in the game if we remove the VoiceID.
![image](https://user-images.githubusercontent.com/74146408/192907905-0b3bd3d2-b50e-4ad5-af7c-d82bfc050d41.png)

**What to do**
Update the functions in PythonLib so that when we extract the story files to XML, we have a new field called "VoiceId" in the XML that hold the voiceId. Changes will need to be done for both NDX and Rebirth.

**Current XML Format**
![image](https://user-images.githubusercontent.com/74146408/192908028-bc17b4cb-bcf0-4c1e-b306-7865e2b5ee5e.png)

**Expected Format**
![image](https://user-images.githubusercontent.com/74146408/192908128-b8948b8f-b90e-4ffa-9339-0b7b855404b0.png)

**User Acceptance Criteria**
The function to extract Story to XMLs should work as expected for NDX and Rebirth

**Comment by Mc-muffin** [comment]
In Rebirth's case, Extraction has been added since 7e4d9f9 and insertion since 5a903c4, NDX and co would need to be updated anyway, so closing this one for now.
